name: CI Pipeline

on:
  push:
    branches: [main] # Corregido: Se añadió el espacio después de los dos puntos
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  NODE_VERSION: "26"
  APP_NAME: cron-ticker

jobs:
  build:
    runs-on: ubuntu-latest # Corregido: Se cambió 'run-on' por 'runs-on'

    env:
      BUILD_DIR: dist

    steps:
      - uses: actions/checkout@v4

      - name: Show Variables
        run: |
          echo "App: ${{ env.APP_NAME }}, Node: ${{ env.NODE_VERSION }}" # Corregido: Se añadieron 4 espacios de sangría

      - name: Build
        run: npm run build
        env:
          APP_VERSION: "2.0.0"

      - name: Run Tests
        run: npm test
